name: ClientWorker 
cleaninterval: 1000*20 # 每20秒检测并清理一次
catch_rules:
    - rule: ^https\:\/\/blog\.xzh\.gs\/js\/
      transform_rules:
        -search: _
         action: skip
    - rule: ^https\:\/\/img\.xzh\.gs\/
      transform_rules:
        - search: _
          action: fetch
          fetch:
            expire: 1000*60*60*24*365
    - rule: ^https\:\/\/tj\.xzh\.gs\/
      transform_rules:
        - search: _
          action: skip
    - rule: ^https\:\/\/cdnjs\.cloudflare\.com\/ajax\/libs
      transform_rules:
        - search: _
          replace:
            - _
            - https://cdn.bootcdn.net/ajax/libs
            - https://lib.baomitu.com
            - https://mirrors.cqupt.edu.cn/cdnjs/ajax/libs # 重庆邮电
            - https://cdn.staticfile.org
            - https://mirrors.sustech.edu.cn/cdnjs/ajax/libs # 南大
            - https://cdnjs.sourcegcdn.com/ajax/libs # 全同步 https://cdnjs.cloudflare.com
        - search: _
          action: fetch
          fetch:
            delay: 200 #请求超时200ms后返回缓存
        - search: ^https\:\/\/((cdn|fastly|gcore)\.jsdelivr\.net|unpkg\.com)
          action: fetch
          fetch:
            expire: 1000*60*60*24*365 #CDN默认缓存一年
        - search: (^5) 
          searchin: status 
          action: return
          return:
            body: The GateWay is down!This Page is provided by ClientWorker!
            status: 503